steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/web/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/elimubora/web'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/elimubora/web'
substitutions:
  _NEXT_PUBLIC_API_URL: 'https://elimubora-api-781329108520.us-central1.run.app'
