// Rotates elimubora_app / elimubora_worker off the hardcoded dev
// passwords migration 0001 creates them with. Intended to run as a
// deploy-time step (e.g. Railway's preDeployCommand) against the
// database owner connection, AFTER migrations have run and BEFORE
// the application itself starts and connects with its real
// (rotated) credentials.
//
// Safe by default: if the rotation env vars aren't present (true for
// every local/dev/CI environment, which never sets them), this is a
// silent no-op rather than an error — those environments are
// expected to keep using migration 0001's dev-only passwords.
import pg from 'pg';

const ownerUrl = process.env.MIGRATIONS_DATABASE_URL;
const appPassword = process.env.APP_ROLE_PASSWORD;
const workerPassword = process.env.WORKER_ROLE_PASSWORD;

if (!ownerUrl || !appPassword || !workerPassword) {
  console.log(
    'rotate-secrets: APP_ROLE_PASSWORD/WORKER_ROLE_PASSWORD/MIGRATIONS_DATABASE_URL not set — skipping (expected in local/CI environments).'
  );
  process.exit(0);
}

// Passwords are generated by us (URL-safe base64: A-Z a-z 0-9 - _) and
// never contain a quote character, but this escapes defensively anyway
// rather than assuming that will always remain true.
const escape = (value) => value.replace(/'/g, "''");

const client = new pg.Client({ connectionString: ownerUrl });
await client.connect();
try {
  await client.query(`ALTER ROLE elimubora_app PASSWORD '${escape(appPassword)}'`);
  await client.query(`ALTER ROLE elimubora_worker PASSWORD '${escape(workerPassword)}'`);
  console.log('rotate-secrets: elimubora_app and elimubora_worker passwords rotated.');
} finally {
  await client.end();
}
